require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ConsultasController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Consulta. As you add validations to Consulta, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConsultasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all consultas as @consultas" do
      consulta = Consulta.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:consultas)).to eq([consulta])
    end
  end

  describe "GET show" do
    it "assigns the requested consulta as @consulta" do
      consulta = Consulta.create! valid_attributes
      get :show, {:id => consulta.to_param}, valid_session
      expect(assigns(:consulta)).to eq(consulta)
    end
  end

  describe "GET new" do
    it "assigns a new consulta as @consulta" do
      get :new, {}, valid_session
      expect(assigns(:consulta)).to be_a_new(Consulta)
    end
  end

  describe "GET edit" do
    it "assigns the requested consulta as @consulta" do
      consulta = Consulta.create! valid_attributes
      get :edit, {:id => consulta.to_param}, valid_session
      expect(assigns(:consulta)).to eq(consulta)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Consulta" do
        expect {
          post :create, {:consulta => valid_attributes}, valid_session
        }.to change(Consulta, :count).by(1)
      end

      it "assigns a newly created consulta as @consulta" do
        post :create, {:consulta => valid_attributes}, valid_session
        expect(assigns(:consulta)).to be_a(Consulta)
        expect(assigns(:consulta)).to be_persisted
      end

      it "redirects to the created consulta" do
        post :create, {:consulta => valid_attributes}, valid_session
        expect(response).to redirect_to(Consulta.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved consulta as @consulta" do
        post :create, {:consulta => invalid_attributes}, valid_session
        expect(assigns(:consulta)).to be_a_new(Consulta)
      end

      it "re-renders the 'new' template" do
        post :create, {:consulta => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested consulta" do
        consulta = Consulta.create! valid_attributes
        put :update, {:id => consulta.to_param, :consulta => new_attributes}, valid_session
        consulta.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested consulta as @consulta" do
        consulta = Consulta.create! valid_attributes
        put :update, {:id => consulta.to_param, :consulta => valid_attributes}, valid_session
        expect(assigns(:consulta)).to eq(consulta)
      end

      it "redirects to the consulta" do
        consulta = Consulta.create! valid_attributes
        put :update, {:id => consulta.to_param, :consulta => valid_attributes}, valid_session
        expect(response).to redirect_to(consulta)
      end
    end

    describe "with invalid params" do
      it "assigns the consulta as @consulta" do
        consulta = Consulta.create! valid_attributes
        put :update, {:id => consulta.to_param, :consulta => invalid_attributes}, valid_session
        expect(assigns(:consulta)).to eq(consulta)
      end

      it "re-renders the 'edit' template" do
        consulta = Consulta.create! valid_attributes
        put :update, {:id => consulta.to_param, :consulta => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested consulta" do
      consulta = Consulta.create! valid_attributes
      expect {
        delete :destroy, {:id => consulta.to_param}, valid_session
      }.to change(Consulta, :count).by(-1)
    end

    it "redirects to the consultas list" do
      consulta = Consulta.create! valid_attributes
      delete :destroy, {:id => consulta.to_param}, valid_session
      expect(response).to redirect_to(consultas_url)
    end
  end

end
